In [63]:
import numpy as np
matrix_a_01 = np.array([1,2,3])
print(matrix_a_01)





[1 2 3]


In [64]:
import numpy as np
matrix_b_01 = np.array([4,5,6])
print(matrix_b_01)

[4 5 6]


In [67]:
import numpy as np
matrix_c_01 = np.array([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
print(matrix_c_01)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [68]:
import numpy as np
matrix_d_01 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix_d_01)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


NameError: name 'np' is not defined

NameError: name 'd' is not defined